version: '3'

services:
  db:
    image: postgres:15
    container_name: luckydraw_db
    ports:
      - '1237:5432'
    volumes:
      - '../db:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: luckydraw
      POSTGRES_USERNAME: $USERNAME
      POSTGRES_PASSWORD: $PASSWORD
    hostname: luckydraw
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 3s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  api-server:
    container_name: luckydraw_api
    build: ../api-server
    ports:
      - '8080:8080'
    hostname: luckydraw
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
